### PR TITLE
Update header

### PR DESCRIPTION
**Pull request by chrisroadmap**
I've made a few changes but otherwise that's all good.

> ahh! I see, that one is for https://github.com/chrisroadmap/ar6/blob/main/data_output/slcf_warming_ranges.csv this file.

Excellent - are the columns still the same in the CSV as in the metadata file?

### CODE REVIEW

**Comment by sarambl** [comment]
Thanks a lot! So I am not totally sure what you mean by the metadata file, but I'll answer what I think the question is: 
The columns are the same as in the original file, except that I dropped scenario and percentile and made each one a separate file. So basically each forcer becomes a column (ch4, o3, etc). I haven't written down all of them in the header (bcs I am lazy), so the ones that are not there will just be generated automatically with default unit "degrees C".

Was that the question?

**Comment by chrisroadmap** [comment]
Yeah, I meant are the variables listed in that file the same ones that are in the dataset? So rows 14 to 68 in https://github.com/sarambl/REWRITE2BADC-CSV/blob/main/rewrite2badc_csv/badc_header_temp/badc_header_FaIR_model_warming.csv give 15 or so column headers that relate to radiative forcing from the forcing time series, but https://github.com/chrisroadmap/ar6/blob/main/data_output/slcf_warming_ranges.csv has columns that related to `index`, `scenario`, `forcing`, `base_period`, `year`, `p05`, `p16`, `p50`, `p84`, `p95`. Do you see what I mean?

**Comment by sarambl** [comment]
Ah, ok! No, the column headers are instead the forcers. So, I flipped them to resemble the other files in SSP. So this is an example for ssp119 and p05: https://github.com/sarambl/REWRITE2BADC-CSV/blob/main/rewrite2badc_csv/data_badc_csv/slcf_warming_ranges/slcf_warming_ranges_ssp119_p05.csv

I.e. index is set to the year, but I drop base_period (same for all), scenario (separate files) and percentile headers (separate files) and then I put the timeseries for each forcer in each column (so somehow select and trick with index and transpose). 

Also: I think I am getting what might be confusing: the header is partly copied from the other ones and there is quite a bit of redundency on the variable side, so in the output file, it only keeps the the info about the colums that are actually written (in this case we only asked for 

aerosol | anthro | bc_on_snow | ch4 | hfc | o3 | slcf
-- | -- | -- | -- | -- | -- | --

so those are the only forcers that you extracted in the slcf_warming_ranges.csv file. 

(I thought i needed to do it like this to fit with the badc format, but now I am not so sure. Might have been fine to have a coordinate variable which has repeating values... )

**Comment by chrisroadmap** [comment]
Excellent, this looks great!

**Pull request merged**
